version: '3.7'
services:
  test-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - RUBY_VERSION=2.6.2
        - RUBY_DOWNLOAD_SHA256=91fcde77eea8e6206d775a48ac58450afe4883af1a42e5b358320beb33a445fa
    image: yndconsult/docker-ruby:2.6.2
