version: '3.7'
services:
  test-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - RUBY_VERSION=2.6.2
    image: yndconsult/docker-ruby:2.6.2-alpine
    
  test-centos:
    build:
      context: .
      dockerfile: Dockerfile.centos
      args:
        - RUBY_VERSION=2.6.2
    image: yndconsult/docker-ruby:2.6.2-centos7
  
  test3-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - RUBY_VERSION=3.0.0
        - DISTRO_VERSION=3.13
    image: yndconsult/docker-ruby:3.0.0-alpine3.13